### ISSUE TITLE
can't import 

### ISSUE THREAD

**Issue by purpshell** [zenje/genius-lyrics-fetcher#2]
... (node:19248) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
Uncaught d:\RetroBot\code_main\retroBot\Main.js:10
import GeniusFetcher from 'genius-lyrics-fetcher';
^^^^^^

SyntaxError: Cannot use import statement outside a module

**Comment by charlie-moomoo** [comment]
The README is wrong, this package uses the `require()` format.
So use `const GeniusFetcher = require('genius-lyrics-fetcher')` instead.

**Comment by purpshell** [comment]
Why would the library use the require format when CommonJS is currently inferior? I got around this by using import = require syntax so that worked then back when it was an issue
